### ISSUE TITLE
No programming skills required?

### ISSUE THREAD

**Issue by Vitali0w0** [laqieer/gbalvns#11]
I think I downloaded all the files and install the things needed, however I really don't know where to start like even which software I should launch. I read the readme files but I still don't know what I should do.
Do you have any advices or links to any tutorial?
Thank you

**Comment by laqieer** [comment]
Did you run `make` in the README? It's basic software installation skill instead of real programming skill. Read [this](https://how-to.fandom.com/wiki/How_to_install_software_from_source) to learn more if you are unfamiliar with it. Notice that we need neither `./configure` before `make` nor `make install` after `make`, so only `make` is required here.
